import type { Karte } from "@/types/karte";

export const DEMO_KARTEN: Karte[] = [
  {
    id: "5",
    slug: "kastilien-und-leon",
    name: "Kastilien und Leon",
    beschreibung:
      "Eine spanische Karte angesiedelt in Kastilien und Leon mit 84 Feldern, 26 kaufbaren Produktionsbetrieben verteilt auf 3 Industriegebiete, 17 Verkaufsstellen und umfangreichen Produktionsketten. Mit 9 Obstbaumsorten, Gewächshäusern (Blumenkohl, Paprika, Gurken, Zucchini), Precision Farming mit eigener Bodenkarte und 25 anpassbaren Landschaftstexturen. Neue Tierrassen mit modifizierten Ställen inkl. Mistbunker. 253 registrierte Gegenstände, 1050 MB. Verfügbar auf PC/Mac, PS5 und Xbox Series.",
    autor: "CyLModdingStudio",
    version: "1.0.0.4",
    groesse: "2x",
    precision_farming: true,
    preview_url: "/images/cyl-preview.jpg",
    minimap_url: "/images/cyl-minimap.png",
    screenshots: [],
    fruechte: [
      "Roggen", "Futterpappel", "Luzerne", "Teffgras", "Lavendel", "Minze",
      "Thymian & Rosmarin", "Apfel", "Orange", "Kirsche", "Pflaume", "Birne",
      "Zitrone", "Granatapfel", "Pfirsich", "Quitte", "Eichel", "Kastanie",
      "Mandel", "Walnuss",
    ],
    produktionen: [],
    pois: [
      { id: "vs-super", name: "Supermercado", typ: "verkaufsstelle", x: 45, y: 35, beschreibung: "Lebensmittel und Produkte" },
      { id: "vs-bar", name: "Bar", typ: "verkaufsstelle", x: 50, y: 40, beschreibung: "Säfte und Snacks" },
      { id: "vs-cafe", name: "Cafeteria", typ: "verkaufsstelle", x: 52, y: 42, beschreibung: "Backwaren und Süßigkeiten" },
      { id: "vs-fruteria", name: "Fruteria", typ: "verkaufsstelle", x: 40, y: 45, beschreibung: "Obst und Gemüse" },
      { id: "vs-rest", name: "Restaurante", typ: "verkaufsstelle", x: 55, y: 38, beschreibung: "Verarbeitete Lebensmittel" },
      { id: "vs-pizza", name: "Pizzeria", typ: "verkaufsstelle", x: 48, y: 50, beschreibung: "Zutaten und Getränke" },
      { id: "vs-burger", name: "Hamburgueseria", typ: "verkaufsstelle", x: 53, y: 48, beschreibung: "Öle, Gemüse und Käse" },
      { id: "vs-eis", name: "Heladeria", typ: "verkaufsstelle", x: 47, y: 43, beschreibung: "Milch, Obst und Schokolade" },
      { id: "vs-farmacia", name: "Farmacia", typ: "verkaufsstelle", x: 58, y: 36, beschreibung: "Medizin und Essenzen" },
      { id: "vs-perfume", name: "Perfumeria", typ: "verkaufsstelle", x: 56, y: 44, beschreibung: "Parfüm und Essenzen" },
      { id: "vs-ropa", name: "Tienda Ropa", typ: "verkaufsstelle", x: 42, y: 52, beschreibung: "Kleidung" },
      { id: "vs-muebles", name: "Tienda Muebles", typ: "verkaufsstelle", x: 60, y: 50, beschreibung: "Möbel und Badewannen" },
      { id: "vs-ferret", name: "Ferreteria", typ: "verkaufsstelle", x: 38, y: 55, beschreibung: "Baumaterial und Holz" },
      { id: "vs-nueces", name: "Frutos Secos", typ: "verkaufsstelle", x: 62, y: 42, beschreibung: "Nüsse und Trockenfrüchte" },
      { id: "vs-agri", name: "Suministros Agricolas", typ: "verkaufsstelle", x: 35, y: 60, beschreibung: "Dünger, Saatgut, Herbizid" },
      { id: "prod-oel", name: "Ölmühle", typ: "produktion", x: 25, y: 30 },
      { id: "prod-zucker", name: "Zuckerfabrik", typ: "produktion", x: 28, y: 35 },
      { id: "prod-saege", name: "Sägewerk", typ: "produktion", x: 70, y: 25 },
      { id: "prod-muehle", name: "Mühle", typ: "produktion", x: 30, y: 50 },
      { id: "prod-molkerei", name: "Molkerei", typ: "produktion", x: 72, y: 55 },
      { id: "prod-destille", name: "Destillerie", typ: "produktion", x: 68, y: 60 },
      { id: "prod-textil", name: "Textilwerk", typ: "produktion", x: 75, y: 45 },
      { id: "prod-bga", name: "Recyclinganlage", typ: "produktion", x: 20, y: 65 },
      { id: "hof1", name: "Granja Inicial (Starthof)", typ: "hof", x: 50, y: 55 },
    ],
    download_url: "https://www.farming-simulator.com/mod.php?mod_id=336009&title=fs2025",
    quell_url: "https://www.farming-simulator.com/mod.php?mod_id=336009&title=fs2025",
    erstellt_am: "2026-03-27T10:00:00Z",
    aktualisiert_am: "2026-03-27T10:00:00Z",
    fakten: {
      felder: 84,
      höfe: 1,
      produktionen: 26,
      verkaufsstellen: 17,
      bga: 1,
      besonderheiten: [
        "Spanisches Setting in Kastilien und Leon",
        "26 Produktionsbetriebe über 3 Industriegebiete",
        "20 Zusatzfrüchte inkl. 9 Obstbaumsorten und Kräutern",
        "Gewächshäuser für Blumenkohl, Paprika, Gurken, Zucchini",
        "Precision Farming mit eigener Bodenkarte",
        "Neue Tierrassen mit modifizierten Ställen (Mistbunker)",
        "25 anpassbare Landschaftstexturen",
        "253 registrierte Gegenstände (1050 MB)",
        "PC/Mac, PS5 und Xbox Series verfügbar",
        "13 Sprachen vollständig übersetzt",
      ],
    },
    durchschnitt_bewertung: 4.9,
    anzahl_bewertungen: 45,
  },
  {
    id: "1",
    slug: "lausitzer-landschaften",
    name: "Lausitzer Landschaften",
    beschreibung:
      "Eine detailreiche 4x Karte aus Ostdeutschland von Turnbeutel Modding. Die Lausitzer Landschaften bieten eine abwechslungsreiche Landschaft mit zahlreichen Produktionsketten, über 30 anbaubaren Früchten inklusive Spezialfrüchten wie Hopfen, Mohn, Sesam und Tabak. Dazu kommen 8 Produktionsbetriebe, 6 Verkaufsstellen und ein realistisches ostdeutsches Flair.",
    autor: "Turnbeutel Modding",
    version: "1.0.8",
    groesse: "4x",
    precision_farming: true,
    preview_url: "/images/lausitzer-preview.jpg",
    minimap_url: "/images/lausitzer-minimap.png",
    screenshots: [],
    fruechte: [
      "Roggen", "Dinkel", "Triticale", "Luzerne", "Klee", "Senf", "Lavendel",
      "Mohn", "Linsen", "Kichererbsen", "Leinsamen", "Flachs", "Hanf", "Tabak",
      "Erdnüsse", "Hopfen", "Sesam",
    ],
    produktionen: [],
    pois: [
      { id: "vs-general", name: "Generalstore", typ: "verkaufsstelle", x: 35, y: 25, beschreibung: "Lebensmittel und Produkte verkaufen" },
      { id: "vs-hardware", name: "Hardwarebob", typ: "verkaufsstelle", x: 55, y: 30, beschreibung: "Getreide und Feldfrüchte verkaufen" },
      { id: "vs-logistic", name: "Lausitz Logistik", typ: "verkaufsstelle", x: 70, y: 45, beschreibung: "Getreide und Feldfrüchte verkaufen" },
      { id: "vs-holz", name: "Lausitz Logistik Holz", typ: "verkaufsstelle", x: 75, y: 50, beschreibung: "Holz verkaufen" },
      { id: "vs-cafe", name: "Central Cafe", typ: "verkaufsstelle", x: 45, y: 55, beschreibung: "Lebensmittel und Produkte verkaufen" },
      { id: "vs-ballen", name: "Lausitzer Ballenankauf", typ: "verkaufsstelle", x: 60, y: 65, beschreibung: "Ballen verkaufen" },
      { id: "prod-diesel", name: "Dieselproduktion", typ: "produktion", x: 30, y: 40, beschreibung: "Biodiesel herstellen" },
      { id: "prod-duenger", name: "Düngerproduktion", typ: "produktion", x: 40, y: 35, beschreibung: "Organischen Dünger produzieren" },
      { id: "prod-herbizid", name: "Herbizidproduktion", typ: "produktion", x: 50, y: 45, beschreibung: "Pflanzenschutzmittel herstellen" },
      { id: "prod-kalk", name: "Kalkwerk", typ: "produktion", x: 25, y: 60, beschreibung: "Kalk produzieren" },
      { id: "prod-liqfert", name: "Flüssigdünger-Fabrik", typ: "produktion", x: 65, y: 35, beschreibung: "Flüssigdünger herstellen" },
      { id: "prod-saatgut", name: "Saatgutfabrik", typ: "produktion", x: 55, y: 60, beschreibung: "Saatgut aufbereiten" },
      { id: "prod-cut", name: "Erdfruchtschnitzelfabrik", typ: "produktion", x: 35, y: 70, beschreibung: "Erdfrüchte verarbeiten" },
      { id: "prod-paletten", name: "Europaletten-Werk", typ: "produktion", x: 80, y: 55, beschreibung: "Paletten und Fässer herstellen" },
      { id: "hof1", name: "Haupthof", typ: "hof", x: 48, y: 48 },
    ],
    download_url: "https://forbidden-mods.de/filebase/file/73797-lausitzer-landschaften-4x/",
    quell_url: "https://forbidden-mods.de/filebase/file/73797-lausitzer-landschaften-4x/",
    erstellt_am: "2026-02-08T10:00:00Z",
    aktualisiert_am: "2026-03-17T10:00:00Z",
    fakten: {
      felder: 130,
      wiesen: 20,
      waelder: 8,
      höfe: 4,
      bauplätze: 2,
      produktionen: 30,
      verkaufsstellen: 6,
      bga: 1,
      besonderheiten: [
        "Echtes Höhenmodell und Satellitenbild der Lausitz (bei Cottbus)",
        "BGA erzeugt Strom, transportierbar per Generatoranhänger",
        "AutoDrive Kurse vorinstalliert",
        "17 Zusatzfrüchte (Multifruit)",
        "Nahe der polnischen Grenze angesiedelt",
      ],
    },
    durchschnitt_bewertung: 4.7,
    anzahl_bewertungen: 38,
  },
  {
    id: "2",
    slug: "hof-bergmann",
    name: "Hof Bergmann",
    beschreibung:
      "Eine detailreiche deutsche Karte mit vielen Produktionen und abwechslungsreichem Gelände. Perfekt für Spieler die eine realistische Landwirtschaftserfahrung suchen.",
    autor: "BergmannModding",
    version: "1.2.0",
    groesse: "4x",
    precision_farming: true,
    preview_url: null,
    minimap_url: null,
    screenshots: [],
    fruechte: [
      "Weizen", "Gerste", "Raps", "Mais", "Kartoffeln",
      "Zuckerrüben", "Hafer", "Sonnenblumen", "Gras", "Luzerne",
    ],
    produktionen: [],
    pois: [
      { id: "hof1", name: "Haupthof", typ: "hof", x: 50, y: 50 },
      { id: "vs1", name: "BGA", typ: "verkaufsstelle", x: 30, y: 70 },
      { id: "prod1", name: "Mühle", typ: "produktion", x: 65, y: 40 },
    ],
    download_url: null,
    quell_url: null,
    erstellt_am: "2025-01-15T10:00:00Z",
    aktualisiert_am: "2025-01-15T10:00:00Z",
    fakten: {
      felder: 80,
      höfe: 3,
      produktionen: 12,
      verkaufsstellen: 4,
    },
    durchschnitt_bewertung: 4.5,
    anzahl_bewertungen: 12,
  },
  {
    id: "3",
    slug: "elmcreek-reloaded",
    name: "Elmcreek Reloaded",
    beschreibung:
      "Eine erweiterte Version der beliebten Elmcreek Karte mit zusätzlichen Feldern, Produktionen und verbesserten Details.",
    autor: "MapModders",
    version: "2.1.0",
    groesse: "2x",
    precision_farming: false,
    preview_url: null,
    minimap_url: null,
    screenshots: [],
    fruechte: [
      "Weizen", "Gerste", "Mais", "Sojabohnen", "Baumwolle", "Sonnenblumen", "Gras",
    ],
    produktionen: [],
    pois: [
      { id: "hof1", name: "Farm", typ: "hof", x: 45, y: 55 },
      { id: "ts1", name: "Tankstelle", typ: "tankstelle", x: 60, y: 30 },
    ],
    download_url: null,
    quell_url: null,
    erstellt_am: "2025-02-20T14:00:00Z",
    aktualisiert_am: "2025-02-20T14:00:00Z",
    fakten: {
      felder: 45,
      höfe: 2,
      produktionen: 6,
      verkaufsstellen: 3,
    },
    durchschnitt_bewertung: 4.2,
    anzahl_bewertungen: 8,
  },
  {
    id: "4",
    slug: "norddeutschland",
    name: "Norddeutschland",
    beschreibung:
      "Eine riesige norddeutsche Marschlandschaft mit weitläufigen Feldern und authentischem Flair. Ideal für Großbetriebe.",
    autor: "NordModding",
    version: "1.0.0",
    groesse: "16x",
    precision_farming: true,
    preview_url: null,
    minimap_url: null,
    screenshots: [],
    fruechte: [
      "Weizen", "Gerste", "Raps", "Kartoffeln", "Zuckerrüben", "Mais", "Gras", "Klee", "Hafer",
    ],
    produktionen: [],
    pois: [
      { id: "hof1", name: "Gutshof", typ: "hof", x: 35, y: 45 },
      { id: "ws1", name: "Werkstatt", typ: "werkstatt", x: 50, y: 60 },
      { id: "hd1", name: "Landhandel", typ: "haendler", x: 70, y: 35 },
    ],
    download_url: null,
    quell_url: null,
    erstellt_am: "2025-03-10T09:00:00Z",
    aktualisiert_am: "2025-03-10T09:00:00Z",
    fakten: {
      felder: 200,
      wiesen: 30,
      waelder: 12,
      höfe: 5,
      produktionen: 8,
      verkaufsstellen: 5,
    },
    durchschnitt_bewertung: 4.8,
    anzahl_bewertungen: 24,
  },
];
